services:
  users:
    command: npm run debug
    ports:
      - "9330-9334:9229"

  promotions:
    command: npm run debug
    ports:
      - "9344-9347:9229"

  notifications:
    command: npm run debug
    ports:
      - "9347-9350:9229"