services:
  users:
    command: npm run debug
    ports:
      - "9229:9229"

  promotions:
    command: npm run debug
    ports:
      - "9230:9229"

  notifications:
    command: npm run debug
    ports:
      - "9231:9229"