version: "3.8"

services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
      - "9229:9229"

  promotions:
    build:
      context: ./promotions
      dockerfile: Dockerfile.debug
    ports:
      - "3001:3001"
      - "9228:9229"